---
- name: Install on Debian system
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family | lower in icinga2_apt_distros

- name: Install on CentOS system
  ansible.builtin.include_tasks: install-Centos.yml
  when: >
    ansible_os_family in ["CentOS", "RedHat", "Red Hat Enterprise Linux"]
    or ansible_distribution_file_variety == "RedHat"
