---
- name: Gather Distribution specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_system }}-{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_system }}-{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_system }}-{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_system }}-{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - vars

# Install dependencies
- import_tasks: install.yml

# Install custom plugins
- import_tasks: plugins.yml
