---
###############################################################################
# Dynamic plugins deploy (automatically managed through icinga2_client_vars)

- name: Create the dynamic plugins destination directory
  ansible.builtin.file:
    path: "{{ icinga2_dynamic_plugins_dest_dir }}"
    state: directory
    recurse: true
    mode: '0750'
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"

###############################################################################
# Plugin list

# Builtin plugins
- name: Install Icinga builtin plugins
  ansible.builtin.include_tasks: plugins/icinga-builtin.yml

# Generic plugins
- name: Install generic Linux plugins
  ansible.builtin.include_tasks: plugins/generic-linux.yml

# Harisekhon Plugins on master node
- name: Install Harisekhon plugins
  ansible.builtin.include_tasks: plugins/harisekhon.yml

# LinuxFabrik Monitoring Plugins
- name: Install LinuxFabrik Monitoring Plugins
  ansible.builtin.include_tasks: plugins/linuxfabrik.yml

# Mail plugins
- name: Install mail plugin
  ansible.builtin.include_tasks: plugins/mail.yml

# MS SQL plugins
- name: Install MS SQL Server plugins
  ansible.builtin.include_tasks: plugins/mssql.yml

# NRPE plugins
- name: Install NRPE plugins
  ansible.builtin.include_tasks: plugins/nrpe.yml

# NVMe plugins
- name: Install NVMe plugins
  ansible.builtin.include_tasks: plugins/nvme.yml

# PostgreSQL plugins
- name: Install PostgreSQL plugins
  ansible.builtin.include_tasks: plugins/postgres.yml

# Proxmox VE plugins
- name: Install Proxmox VE plugins
  ansible.builtin.include_tasks: plugins/pve.yml

# Samba AD plugins
- name: Install Samba Active Directory plugins
  ansible.builtin.include_tasks: plugins/samba_ad.yml

# SSSD plugins
- name: Install SSSD plugins
  ansible.builtin.include_tasks: plugins/sssd.yml

# Samba plugins
- name: Install Samba plugins
  ansible.builtin.include_tasks: plugins/samba.yml

# ZFS plugins
- name: Install ZFS plugins
  ansible.builtin.include_tasks: plugins/zfs.yml
