---
###############################################################################
# Plugins deploy

- name: Create the plugins destination directory
  ansible.builtin.file:
    path: "{{ icinga2_plugins_dest_dir }}"
    state: directory
    recurse: true
    mode: '0750'
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"

- name: Create the icons destination directory
  ansible.builtin.file:
    path: "{{ icinga2_plugins_icons_dir_path }}/plugins"
    state: directory
    mode: '0755'
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"

###############################################################################
# Plugin list

# Builtin plugins
- name: Install Icinga builtin plugins
  ansible.builtin.include_tasks: plugins/linux/icinga-builtin.yml

# Generic plugins
- name: Install generic Linux plugins
  ansible.builtin.include_tasks: plugins/linux/generic-linux.yml

# Always OK
- name: Install Always OK plugin
  ansible.builtin.include_tasks: plugins/linux/always-ok.yml

# Harisekhon Plugins on master node
- name: Install Harisekhon plugins
  ansible.builtin.include_tasks: plugins/linux/harisekhon.yml

# LinuxFabrik Monitoring Plugins
- name: Install LinuxFabrik Monitoring Plugins
  ansible.builtin.include_tasks: plugins/linux/linuxfabrik.yml

# Mail plugins
- name: Install mail plugin
  ansible.builtin.include_tasks: plugins/linux/mail.yml

# MS SQL plugins
- name: Install MS SQL Server plugins
  ansible.builtin.include_tasks: plugins/linux/mssql.yml

# NRPE plugins
- name: Install NRPE plugins
  ansible.builtin.include_tasks: plugins/linux/nrpe.yml

# NVMe plugins
- name: Install NVMe plugins
  ansible.builtin.include_tasks: plugins/linux/nvme.yml

# PostgreSQL plugins
- name: Install PostgreSQL plugins
  ansible.builtin.include_tasks: plugins/linux/postgres.yml

# Proxmox VE plugins
- name: Install Proxmox VE plugins
  ansible.builtin.include_tasks: plugins/linux/pve.yml

# Samba AD plugins
- name: Install Samba Active Directory plugins
  ansible.builtin.include_tasks: plugins/linux/samba_ad.yml

# SSSD plugins
- name: Install SSSD plugins
  ansible.builtin.include_tasks: plugins/linux/sssd.yml

# Samba plugins
- name: Install Samba plugins
  ansible.builtin.include_tasks: plugins/linux/samba.yml

# ZFS plugins
- name: Install ZFS plugins
  ansible.builtin.include_tasks: plugins/linux/zfs.yml
