---
###############################################################################
# Windows plugin list

# Builtin plugins
- name: Install Icinga builtin plugins
  ansible.builtin.include_tasks: plugins/windows/windows-builtin.yml
