---
- include_tasks: plugins-Linux.yml
  when: ansible_system == "Linux"

- include_tasks: plugins-Windows.yml
  when: ansible_os_family == "Windows"

- include_tasks: plugins/samba_ad.yml
  when: icinga2_client_vars.samba_ad is defined
