---
- include_tasks: plugins-Linux.yml
  when: ansible_system == "Linux"

- include_tasks: plugins-Windows.yml
  when: ansible_os_family == "Windows"

# Samba AD plugins
- include_tasks: plugins/samba_ad.yml
  when: icinga2_client_vars.samba_ad is defined or ansible_fqdn == icinga2_master_inventory_hostname

# PostgreSQL plugins
- include_tasks: plugins/postgres.yml
  when: icinga2_client_vars.postgres is defined or ansible_fqdn == icinga2_master_inventory_hostname

# SSSD plugins
- include_tasks: plugins/sssd.yml
  when: icinga2_client_vars.sssd is defined or ansible_fqdn == icinga2_master_inventory_hostname

# MS SQL plugins
- include_tasks: plugins/mssql.yml
  when: icinga2_client_vars.mssql is defined or ansible_fqdn == icinga2_master_inventory_hostname

# NRPE plugins
- include_tasks: plugins/nrpe.yml
  when: icinga2_client_vars.nrpe is defined or ansible_fqdn == icinga2_master_inventory_hostname

# Samba plugins
- include_tasks: plugins/samba.yml
  when: icinga2_client_vars.samba_share is defined or ansible_fqdn == icinga2_master_inventory_hostname

# Mail plugins
- include_tasks: plugins/mail.yml
  when: icinga2_client_vars.mailq is defined or ansible_fqdn == icinga2_master_inventory_hostname
