---
- name: Install plugins on Linux systems
  ansible.builtin.include_tasks: plugins-Linux.yml
  when: ansible_system == "Linux"

- name: Install plugins on Windows systems
  ansible.builtin.include_tasks: plugins-Windows.yml
  when: ansible_os_family == "Windows"
